name: Deploy to ECS Fargate

on:
  workflow_dispatch:
    inputs:
      Runner:
        description: GitHub runner
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: ecs-fargate
  ECR_REPOSITORY: ecs-test
  IMAGE_TAG: latest
  ACCOUNT_ID: 890742570780
  CONTAINER_PORT: 3000
  STACK_NAME: ecs-test-stack
  ECS_CLUSTER_NAME: ecs-fargate-cluster
  ECS_CONTAINER_NAME: ecs-fargate-container

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ${{ github.event.inputs.Runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "Building image $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "ECR_IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Make deploy script executable
        run: chmod +x ./ecs-fargate.sh

      - name: Deploy CloudFormation stack
        run: ./ecs-fargate.sh
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          ECS_CLUSTER_NAME: ${{ env.ECS_CLUSTER_NAME }}
          ECS_CONTAINER_NAME: ${{ env.ECS_CONTAINER_NAME }}
          ECR_IMAGE_URI: ${{ env.ECR_IMAGE_URI }}    # <-- This now uses the runtime variable set above
          CONTAINER_PORT: ${{ env.CONTAINER_PORT }}
          STACK_NAME: ${{ env.STACK_NAME }}
